language: node_js
node_js:
  - 0.12
env:
  global:
  - GH_REF: github.com/hugeinc/styleguide.git
script:
  - chmod +x deploy.sh build.sh
  - npm install harp -g
  - npm install jspm -g
  - bash ./deploy.sh