language: node_js
node_js:
  - 0.12
env:
  global:
  - GH_REF: github.com/hugeinc/styleguide.git
  - secure: "eSG9lYCQSQrYzbodDpM0Vv1MgwJarhIINQBOmXNpA6xNoLx5/PYr+DowrclmlEMmhFmZ4D3fovBtrePoF2TvXYOC0NPbuqErJBJqI9m3TdVJRsr5OE1u3tnJvGR8RbT6aR2JrlDfHiM2eQ6hml5DvQX1ZzMMyd7ovSA+j5XKmAmxeMkKgPm0A5llGzDkGvyeUjF8yz3ZrcYx+CcdWLVUbbheb23HMcCd5cXpJVxriW+5ENLSwZtljuXVED0Q8J83Iw9YZxaU3fsyrRQMXrzGe5xOvZPqyBjp1m0C3WjHyj5ZZdBcEiRF6R33GvCkFZOybpGkdcIR+gbWCGi97kYSJDXMaWwsau9ijVCcSLsze2DMlLdvAQFbgjfjYCTHuJRcDXA175huckOjTjaFPLLHG0Eogy5INg4b/xp7bRfQ7zpxsebqD0N/k+bQWCS4+IXlzYuvFsiBEBCZmZk/rKsDPbhu3Pa5p/WS4ilBm2X2SAKNv8MQ0em3Pi1NVUYHUZLN60Tz4hgmSlSlwAYl7P3/oD5cGcCKHc5p9SnPuMtuAMUf7mhZsoGAbCbbfziAyAvlG0QSh6QhrqloDmvTQ6C37IbNsHRYBVPrCc28H0HS7IjYTznS7KL5AWea1Ie2S1HFPx9Av3QzDHu9FtZ1ttWPYygyJjdT5UtMg7aDrHtthxc="
script:
  - chmod +x deploy.sh build.sh
  - npm install harp -g
  - npm install jspm -g
  - bash ./deploy.sh